/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockStrategyA__factory } from "./MockStrategyA__factory";
export { MockStrategyB__factory } from "./MockStrategyB__factory";
